name: Build

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw -B -ntp package

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: quarkus-app
          path: |
            target/*-runner.jar
          if-no-files-found: ignore
