name: Build Windows Installer

on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths:
      - "**/*.java"
      - "pom.xml"
      - ".github/workflows/windows-installer.yml"
      - "scripts/windows/**"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Make Maven Wrapper executable (Git Bash compatibility)
        run: git update-index --chmod=+x mvnw

      - name: Build Windows installer (.exe) via Maven plugin
        shell: pwsh
        run: |
          ./mvnw -B -ntp -Dquarkus.package.jar.type=uber-jar -Pwindows-release package

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: |
            target/*.exe
          if-no-files-found: error
